export const Gents ={
    title:"Gents Fashion",
    image1:"assests/men/1.jpg",
    image2:"assests/men/2.jpg",
    image3:"assests/men/3.jpg",
    image4:"assests/men/4.jpg",
    image5:"assests/men/5.jpg",
    image6:"assests/men/6.jpg",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR",
    price6:"959 INR",
}
export const Ladies ={
    title:"Ladies Fashion",
    image1:"assests/women/1.jpg",
    image2:"assests/women/2.jpg",
    image3:"assests/women/3.jpg",
    image4:"assests/women/4.jpg",
    image5:"assests/women/5.jpg",
    image6:"assests/women/6.jpg",    
    image7:"assests/women/7.jpg",    
    image8:"assests/women/8.jpg",    
    price1:"1559 INR",
    price2:"1459 INR",
    price3:"1659 INR",
    price4:"1759 INR",
    price5:"1859 INR",
    price6:"1959 INR",
}